"""Initialized tables

Revision ID: 241808c91694
Revises:
Create Date: 2026-04-22 12:01:26.344435

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '241808c91694'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table('users',
                  sa.Column('uid', sa.String(length=6), nullable=False),
                  sa.Column('email', sa.String(length=255), nullable=False),
                  sa.Column('password', sa.String(length=255), nullable=False),
                  sa.Column('is_active', sa.Boolean(), nullable=False),
                  sa.Column('is_blocked', sa.Boolean(), nullable=False),
                  sa.Column('roles', sa.JSON(), nullable=True),
                  sa.Column('scopes', sa.JSON(), nullable=True),
                  sa.Column('updated', sa.DateTime(), nullable=False),
                  sa.Column('created', sa.DateTime(), nullable=False),
                  sa.PrimaryKeyConstraint('uid'),
                  mysql_collate='utf8mb4_general_ci',
                  mysql_default_charset='utf8mb4')
  op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
  op.create_table('refresh_tokens',
                  sa.Column('id', sa.String(length=36), nullable=False),
                  sa.Column('user_uid', sa.String(length=6), nullable=False),
                  sa.Column('token', sa.String(length=64), nullable=False),
                  sa.Column('expires_at', sa.DateTime(), nullable=False),
                  sa.Column('revoked', sa.Boolean(), nullable=False),
                  sa.Column('created', sa.DateTime(), nullable=False),
                  sa.ForeignKeyConstraint(
                      ['user_uid'],
                      ['users.uid'],
                  ),
                  sa.PrimaryKeyConstraint('id'),
                  mysql_collate='utf8mb4_general_ci',
                  mysql_default_charset='utf8mb4')
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_table('refresh_tokens')
  op.drop_index(op.f('ix_users_email'), table_name='users')
  op.drop_table('users')
  # ### end Alembic commands ###
